### PR TITLE
Add Nebra

### PR DESCRIPTION
**Pull request by shawaj**
Add Nebra

### CODE REVIEW

**Comment by rawrmaan** [comment]
Can you remove one of the entries? Since the `router_key` and `escrow_account` are the same, the entries are redundant.

**Comment by shawaj** [comment]
> Can you remove one of the entries? Since the `router_key` and `escrow_account` are the same, the entries are redundant.

They are separate OUIs though? 

One using our own NetID (459) and one using foundation NetID (921)

**Comment by shawaj** [comment]
But can remove one if that's better of course. Just wasn't sure.

**Comment by rawrmaan** [comment]
`id` isn't really used for anything other then collision avoidance, so no worries. I don't think any consumers of this list are looking up by `id`

**Comment by shawaj** [comment]
I could add it as a list if you want, like:

`"id": [459, 921],`

but maybe that's overkill / not sure if that'll break anything else?

**Comment by rawrmaan** [comment]
I would just keep the `921` since it's the newest. I want to avoid introducing a new data type into the `id` field

**Comment by shawaj** [comment]
@rawrmaan no probs, all done now...

**Comment by rawrmaan** [comment]
LGTM, thanks!

**Pull request merged**
